"""Hardware-free semantic instructions generated by a competition policy."""

from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Mapping


@dataclass(frozen=True)
class ActionSpec:
    kind: str
    name: str
    profile: str
    parameters: Mapping = field(default_factory=dict)
    requires_anchor: str | None = None
    ends_at: str | None = None

    def __post_init__(self):
        if not self.kind or not self.name or not self.profile:
            raise ValueError('action kind, name and profile must be nonempty')
        values = dict(self.parameters)
        if any(not isinstance(key, str) or
               not isinstance(value, (str, int, float, bool, type(None)))
               for key, value in values.items()):
            raise TypeError('action parameters must be named scalar values')
        object.__setattr__(self, 'parameters', MappingProxyType(values))
